name = "cloudflare-container-app"
main = "src/index.ts"
compatibility_date = "2025-01-03"

[[containers]]
binding = "CONTAINER"
class_name = "MyContainer"
image = "$CONTAINER_IMAGE"

[vars]
# Add any environment variables your container needs here