name = "cloudflare-container-app"
main = "src/index.ts"
compatibility_date = "2025-01-03"

[[containers]]
binding = "MYCONTAINER"
image = "CONTAINER_IMAGE_PLACEHOLDER"

[vars]
# Add any environment variables your container needs here