name = "cloudflare-container-app"
main = "src/index.ts"
compatibility_date = "2025-01-03"

[[durable_objects.bindings]]
name = "MY_CONTAINER"
class_name = "MyContainer"

[[migrations]]
tag = "v1"
new_classes = ["MyContainer"]

[[containers]]
binding = "CONTAINER"
class_name = "MyContainer"
image = "CONTAINER_IMAGE_PLACEHOLDER"

[vars]
# Add any environment variables your container needs here